// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for Role.
const (
	Admin  Role = "admin"
	Member Role = "member"
	Owner  Role = "owner"
)

// Defines values for TaskStatus.
const (
	Done       TaskStatus = "done"
	InProgress TaskStatus = "in_progress"
	Todo       TaskStatus = "todo"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	AssigneeId  *int64      `json:"assignee_id"`
	Description *string     `json:"description,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	TeamId      int64       `json:"team_id"`
	Title       string      `json:"title"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// IDResponse defines model for IDResponse.
type IDResponse struct {
	Id int64 `json:"id"`
}

// InviteRequest defines model for InviteRequest.
type InviteRequest struct {
	// Email Email address used by mocked external invite service.
	Email  *openapi_types.Email `json:"email,omitempty"`
	Role   Role                 `json:"role"`
	UserId int64                `json:"user_id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token JWT access token
	Token string `json:"token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// ReportsResponse defines model for ReportsResponse.
type ReportsResponse struct {
	InvalidAssignees []Task       `json:"invalid_assignees"`
	TeamStats        []TeamStats  `json:"team_stats"`
	TopCreators      []TopCreator `json:"top_creators"`
}

// Role defines model for Role.
type Role string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// Task defines model for Task.
type Task struct {
	AssigneeId  *int64     `json:"assignee_id"`
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   int64      `json:"created_by"`
	Description string     `json:"description"`
	Id          int64      `json:"id"`
	Status      TaskStatus `json:"status"`
	TeamId      int64      `json:"team_id"`
	Title       string     `json:"title"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// TaskComment defines model for TaskComment.
type TaskComment struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	TaskId    int64     `json:"task_id"`
	UserId    int64     `json:"user_id"`
}

// TaskHistory defines model for TaskHistory.
type TaskHistory struct {
	ChangedBy int64     `json:"changed_by"`
	CreatedAt time.Time `json:"created_at"`
	Field     string    `json:"field"`
	Id        int64     `json:"id"`
	NewValue  string    `json:"new_value"`
	OldValue  string    `json:"old_value"`
	TaskId    int64     `json:"task_id"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time `json:"created_at"`
	CreatedBy int64     `json:"created_by"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	Role      *Role     `json:"role,omitempty"`
}

// TeamStats defines model for TeamStats.
type TeamStats struct {
	DoneLast7Days int64  `json:"done_last_7_days"`
	Members       int64  `json:"members"`
	Name          string `json:"name"`
	TeamId        int64  `json:"team_id"`
}

// TopCreator defines model for TopCreator.
type TopCreator struct {
	CreatedTasks int64               `json:"created_tasks"`
	Email        openapi_types.Email `json:"email"`
	Rank         int64               `json:"rank"`
	TeamId       int64               `json:"team_id"`
	UserId       int64               `json:"user_id"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	AssigneeId  *int64      `json:"assignee_id"`
	Description *string     `json:"description,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	Title       *string     `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        int64               `json:"id"`
	Name      string              `json:"name"`
}

// TaskID defines model for TaskID.
type TaskID = int64

// TeamID defines model for TeamID.
type TeamID = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	TeamId     int64       `form:"team_id" json:"team_id"`
	Status     *TaskStatus `form:"status,omitempty" json:"status,omitempty"`
	AssigneeId *int64      `form:"assignee_id,omitempty" json:"assignee_id,omitempty"`
	Limit      *int        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int        `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// InviteUserJSONRequestBody defines body for InviteUser for application/json ContentType.
type InviteUserJSONRequestBody = InviteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login and receive JWT
	// (POST /api/v1/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Register user
	// (POST /api/v1/register)
	Register(w http.ResponseWriter, r *http.Request)
	// Complex SQL reports
	// (GET /api/v1/reports)
	Reports(w http.ResponseWriter, r *http.Request)
	// List tasks with filters and pagination
	// (GET /api/v1/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams)
	// Create task
	// (POST /api/v1/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// Update task
	// (PUT /api/v1/tasks/{id})
	UpdateTask(w http.ResponseWriter, r *http.Request, id TaskID)
	// Task history
	// (GET /api/v1/tasks/{id}/history)
	TaskHistory(w http.ResponseWriter, r *http.Request, id TaskID)
	// List current user's teams
	// (GET /api/v1/teams)
	ListTeams(w http.ResponseWriter, r *http.Request)
	// Create team
	// (POST /api/v1/teams)
	CreateTeam(w http.ResponseWriter, r *http.Request)
	// Invite user to team
	// (POST /api/v1/teams/{id}/invite)
	InviteUser(w http.ResponseWriter, r *http.Request, id TeamID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login and receive JWT
// (POST /api/v1/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register user
// (POST /api/v1/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complex SQL reports
// (GET /api/v1/reports)
func (_ Unimplemented) Reports(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tasks with filters and pagination
// (GET /api/v1/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create task
// (POST /api/v1/tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update task
// (PUT /api/v1/tasks/{id})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, id TaskID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Task history
// (GET /api/v1/tasks/{id}/history)
func (_ Unimplemented) TaskHistory(w http.ResponseWriter, r *http.Request, id TaskID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List current user's teams
// (GET /api/v1/teams)
func (_ Unimplemented) ListTeams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create team
// (POST /api/v1/teams)
func (_ Unimplemented) CreateTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invite user to team
// (POST /api/v1/teams/{id}/invite)
func (_ Unimplemented) InviteUser(w http.ResponseWriter, r *http.Request, id TeamID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Reports operation middleware
func (siw *ServerInterfaceWrapper) Reports(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Reports(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Required query parameter "team_id" -------------

	if paramValue := r.URL.Query().Get("team_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_id", r.URL.Query(), &params.TeamId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "assignee_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "assignee_id", r.URL.Query(), &params.AssigneeId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignee_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TaskHistory operation middleware
func (siw *ServerInterfaceWrapper) TaskHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TaskHistory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTeams operation middleware
func (siw *ServerInterfaceWrapper) ListTeams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InviteUser operation middleware
func (siw *ServerInterfaceWrapper) InviteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InviteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/reports", wrapper.Reports)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/tasks/{id}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks/{id}/history", wrapper.TaskHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/teams", wrapper.ListTeams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/teams", wrapper.CreateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/teams/{id}/invite", wrapper.InviteUser)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type RateLimitedJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response Login422JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse struct{ InternalErrorJSONResponse }

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse IDResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Register400JSONResponse struct{ BadRequestJSONResponse }

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Register409JSONResponse struct{ ConflictJSONResponse }

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type Register422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response Register422JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type Register500JSONResponse struct{ InternalErrorJSONResponse }

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReportsRequestObject struct {
}

type ReportsResponseObject interface {
	VisitReportsResponse(w http.ResponseWriter) error
}

type Reports200JSONResponse ReportsResponse

func (response Reports200JSONResponse) VisitReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Reports401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Reports401JSONResponse) VisitReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Reports429JSONResponse struct{ RateLimitedJSONResponse }

func (response Reports429JSONResponse) VisitReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type Reports500JSONResponse struct{ InternalErrorJSONResponse }

func (response Reports500JSONResponse) VisitReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTasksRequestObject struct {
	Params ListTasksParams
}

type ListTasksResponseObject interface {
	VisitListTasksResponse(w http.ResponseWriter) error
}

type ListTasks200ResponseHeaders struct {
	XCache string
}

type ListTasks200JSONResponse struct {
	Body    []Task
	Headers ListTasks200ResponseHeaders
}

func (response ListTasks200JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Cache", fmt.Sprint(response.Headers.XCache))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListTasks400JSONResponse struct{ BadRequestJSONResponse }

func (response ListTasks400JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListTasks401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTasks401JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListTasks403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListTasks403JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListTasks422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ListTasks422JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ListTasks429JSONResponse struct{ RateLimitedJSONResponse }

func (response ListTasks429JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type ListTasks500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTasks500JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTaskRequestObject struct {
	Body *CreateTaskJSONRequestBody
}

type CreateTaskResponseObject interface {
	VisitCreateTaskResponse(w http.ResponseWriter) error
}

type CreateTask201JSONResponse IDResponse

func (response CreateTask201JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTask400JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateTask401JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateTask403JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateTask422JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask429JSONResponse struct{ RateLimitedJSONResponse }

func (response CreateTask429JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type CreateTask500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTask500JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTaskRequestObject struct {
	Id   TaskID `json:"id"`
	Body *UpdateTaskJSONRequestBody
}

type UpdateTaskResponseObject interface {
	VisitUpdateTaskResponse(w http.ResponseWriter) error
}

type UpdateTask200JSONResponse StatusResponse

func (response UpdateTask200JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateTask400JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateTask401JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateTask403JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateTask404JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask429JSONResponse struct{ RateLimitedJSONResponse }

func (response UpdateTask429JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTask500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateTask500JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type TaskHistoryRequestObject struct {
	Id TaskID `json:"id"`
}

type TaskHistoryResponseObject interface {
	VisitTaskHistoryResponse(w http.ResponseWriter) error
}

type TaskHistory200JSONResponse []TaskHistory

func (response TaskHistory200JSONResponse) VisitTaskHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TaskHistory401JSONResponse struct{ UnauthorizedJSONResponse }

func (response TaskHistory401JSONResponse) VisitTaskHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type TaskHistory403JSONResponse struct{ ForbiddenJSONResponse }

func (response TaskHistory403JSONResponse) VisitTaskHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type TaskHistory404JSONResponse struct{ NotFoundJSONResponse }

func (response TaskHistory404JSONResponse) VisitTaskHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TaskHistory429JSONResponse struct{ RateLimitedJSONResponse }

func (response TaskHistory429JSONResponse) VisitTaskHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type TaskHistory500JSONResponse struct{ InternalErrorJSONResponse }

func (response TaskHistory500JSONResponse) VisitTaskHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTeamsRequestObject struct {
}

type ListTeamsResponseObject interface {
	VisitListTeamsResponse(w http.ResponseWriter) error
}

type ListTeams200JSONResponse []Team

func (response ListTeams200JSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTeams401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTeams401JSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListTeams429JSONResponse struct{ RateLimitedJSONResponse }

func (response ListTeams429JSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type ListTeams500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTeams500JSONResponse) VisitListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeamRequestObject struct {
	Body *CreateTeamJSONRequestBody
}

type CreateTeamResponseObject interface {
	VisitCreateTeamResponse(w http.ResponseWriter) error
}

type CreateTeam201JSONResponse IDResponse

func (response CreateTeam201JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTeam400JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateTeam401JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateTeam422JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam429JSONResponse struct{ RateLimitedJSONResponse }

func (response CreateTeam429JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTeam500JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InviteUserRequestObject struct {
	Id   TeamID `json:"id"`
	Body *InviteUserJSONRequestBody
}

type InviteUserResponseObject interface {
	VisitInviteUserResponse(w http.ResponseWriter) error
}

type InviteUser200JSONResponse StatusResponse

func (response InviteUser200JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser400JSONResponse struct{ BadRequestJSONResponse }

func (response InviteUser400JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response InviteUser401JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response InviteUser403JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser404JSONResponse struct{ NotFoundJSONResponse }

func (response InviteUser404JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser409JSONResponse struct{ ConflictJSONResponse }

func (response InviteUser409JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response InviteUser422JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser429JSONResponse struct{ RateLimitedJSONResponse }

func (response InviteUser429JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type InviteUser500JSONResponse struct{ InternalErrorJSONResponse }

func (response InviteUser500JSONResponse) VisitInviteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login and receive JWT
	// (POST /api/v1/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Register user
	// (POST /api/v1/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Complex SQL reports
	// (GET /api/v1/reports)
	Reports(ctx context.Context, request ReportsRequestObject) (ReportsResponseObject, error)
	// List tasks with filters and pagination
	// (GET /api/v1/tasks)
	ListTasks(ctx context.Context, request ListTasksRequestObject) (ListTasksResponseObject, error)
	// Create task
	// (POST /api/v1/tasks)
	CreateTask(ctx context.Context, request CreateTaskRequestObject) (CreateTaskResponseObject, error)
	// Update task
	// (PUT /api/v1/tasks/{id})
	UpdateTask(ctx context.Context, request UpdateTaskRequestObject) (UpdateTaskResponseObject, error)
	// Task history
	// (GET /api/v1/tasks/{id}/history)
	TaskHistory(ctx context.Context, request TaskHistoryRequestObject) (TaskHistoryResponseObject, error)
	// List current user's teams
	// (GET /api/v1/teams)
	ListTeams(ctx context.Context, request ListTeamsRequestObject) (ListTeamsResponseObject, error)
	// Create team
	// (POST /api/v1/teams)
	CreateTeam(ctx context.Context, request CreateTeamRequestObject) (CreateTeamResponseObject, error)
	// Invite user to team
	// (POST /api/v1/teams/{id}/invite)
	InviteUser(ctx context.Context, request InviteUserRequestObject) (InviteUserResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Reports operation middleware
func (sh *strictHandler) Reports(w http.ResponseWriter, r *http.Request) {
	var request ReportsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Reports(ctx, request.(ReportsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Reports")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportsResponseObject); ok {
		if err := validResponse.VisitReportsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTasks operation middleware
func (sh *strictHandler) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	var request ListTasksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTasks(ctx, request.(ListTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTasksResponseObject); ok {
		if err := validResponse.VisitListTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTask operation middleware
func (sh *strictHandler) CreateTask(w http.ResponseWriter, r *http.Request) {
	var request CreateTaskRequestObject

	var body CreateTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTask(ctx, request.(CreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTaskResponseObject); ok {
		if err := validResponse.VisitCreateTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTask operation middleware
func (sh *strictHandler) UpdateTask(w http.ResponseWriter, r *http.Request, id TaskID) {
	var request UpdateTaskRequestObject

	request.Id = id

	var body UpdateTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTask(ctx, request.(UpdateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTaskResponseObject); ok {
		if err := validResponse.VisitUpdateTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TaskHistory operation middleware
func (sh *strictHandler) TaskHistory(w http.ResponseWriter, r *http.Request, id TaskID) {
	var request TaskHistoryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TaskHistory(ctx, request.(TaskHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TaskHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TaskHistoryResponseObject); ok {
		if err := validResponse.VisitTaskHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTeams operation middleware
func (sh *strictHandler) ListTeams(w http.ResponseWriter, r *http.Request) {
	var request ListTeamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTeams(ctx, request.(ListTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTeams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTeamsResponseObject); ok {
		if err := validResponse.VisitListTeamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTeam operation middleware
func (sh *strictHandler) CreateTeam(w http.ResponseWriter, r *http.Request) {
	var request CreateTeamRequestObject

	var body CreateTeamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTeam(ctx, request.(CreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTeamResponseObject); ok {
		if err := validResponse.VisitCreateTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InviteUser operation middleware
func (sh *strictHandler) InviteUser(w http.ResponseWriter, r *http.Request, id TeamID) {
	var request InviteUserRequestObject

	request.Id = id

	var body InviteUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InviteUser(ctx, request.(InviteUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InviteUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InviteUserResponseObject); ok {
		if err := validResponse.VisitInviteUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3W4ctxV+FYIt0JuJdiXZjbu9aaLYiASlSSW5LmAIEjVzdpfRzHBMcmSpwgL+QZGL",
	"GPVNX6BvoDpxrcaW8gqcNypIzu/OrPZXimDkJvHODA/P//nOIXWKXRZELIRQCtw5xRHhJAAJ3PzaIeJw",
	"/Qv9Lw+Ey2kkKQtxxzxH619gB1P9MyKyjx0ckgBwB1MPO5jDk5hy8HBH8hgcLNw+BERT6jIeEKm/C+Xv",
	"72AHBzSkQRzgzrKD5UkE9hX0gOPBwME7QIJGHoAEN8PDQJMSEQsFGK18TrwteBKDkPqXy0IJofkniSKf",
	"ukQz2PpWaC5PMRyTIPLtwgPibaSPj4gfg3nPOeO4o98hs8bsV7D6Ww5d3MG/aRV2atm3onVfr91KWbML",
	"qzpaD4+ITz3ELbvogHkniHFUsvLAwWss7PrUnVYat7SsJk7+cpHibIFgMXcBFdQd/IDxA+p5EE7Jfre8",
	"rsZ/8XaRAqzFnEMoUSyAoz4RKGQo81IUAQ+oEJSFxirroQQeEv++5Wgq2Wi6tlG07CWyDxbrbylpAfwI",
	"eLaDg//M5AMWh96UcoSlZTU5QiZR17y9Fh8rkXfwFpGwSQMqYVoReHVlTQr9Hvn6g8WKkZNFcOwCeGDk",
	"eBiSWPYZp3+fWpB4aGlNksoHi5TlKx0VYc9BNE1njCM4jkzQbDzasXJFnLkgBDnw4X4oqTyZUjxDmdgd",
	"G4QrXl9D2Py1TjyjbXhb40Ak6KJbqjsRZxFwSS37RAjaCwH2qFeSDHfuOlcXuzD2fa2zrEYOF78hVnUR",
	"7pLY1+SwU2yDP/M8tP2XTcQhYlwKBKEXMRpKnJMUktOwpykKSWQsxmlNi7ttvxw4WAIJhmVbdqYr5A6W",
	"VPpQoYHX9f8DnZRT1jURcrwJYU/2cWfl7l1DNPu9XJNnUAYaj3NGs8128wXs4FuwJSu1J5BgpD0tjikz",
	"+o1PpBZ3Tv4M4Samql5aYwiyMlRwVNTIcZvaxU27rn8xessJzN2AF8v7Uq950/CIShipewgI9euA875+",
	"jIjncRBCl3APHZyggLmH4CE4TisfNbRNAaQuLFWCJIDgAPif0gdLLtPGzGWy2zbEC2fWaa+Kli39zcDB",
	"GllMmwPGKDEjmTLSpNBN1qPheH0WmmBPwxkUEREhnjJelQ4LcDnI5ZXVMo3807GumW6WL7hCvlGOKtkh",
	"hHWH2Xi0g4irqxKyX4zNHearJga2oEeFBH79Oq4nnq81HTwmy8xqnBLRe5OayrA4xmJbNplfkVwsltjL",
	"Cqd9KCGYqDCZYmL3JJyTk7xE6do2BSkgwbZZ0USPRXuurhSMT0GRRWt2TZ1kU6Wy/A5t5jRop1HJaWKC",
	"UGeSx9bjsIOJF1Dt7Tbf6aXDObDJ82yxH22xAjaUfPxwbFCly5r4N5acC0qNh09GqeDtEVkZPHhEwieS",
	"GkeuaSJbc3AydQGs4bXZINpw6W1PtPV1AruZwVxNtjjyprRIHVU4NZxXVXyui4oxK95QYWSUd66xIEgb",
	"mKqTHjDvZBgfAhGA3D64h0j2qUCSiMOlq/xrGp8cMtGdlclsRMTh3mzONCmSGQ8BCzacEpgxGqzoYpQR",
	"vqRCMn5SN4LbJ2Fv1jidxQhdCv5wgc38bHwMT6b3EJ7uFe1vvo/HwkaWmO81fS6Zx5o+n9khrjZryRKZ",
	"lsqslaWayOTbeSYr+t1UpKzYpT9puBdx1tM9gc4BWkuVejdKEbr0N3jUTVeLmTLvlc3pHO1Lk41TsDcq",
	"izYaMEdVNf1q++z5RMi9T/c8clJFE8t3JpLeIpjq0k+vQW+zVsaRA4lUlRn/Tl0bjdosEOVId9WBWFXI",
	"vYkU0tC1pCB0+iaZhIfjp0Pk2Ha9q2MnRTPDkqa6tTqP2YqSlQlfVXsqe5PtHhqEcTsGh6OBKAk9JEE0",
	"o7WZMOUEyLAMf6edp9X1LIAvJpkvrI9fUGLPmv8JEPFQe35lktaGBTfmVJ5saxOmoBYIB/5ZrBWf/XqQ",
	"cb3xaAenU3FNyb4tOOtLGdnZOg27rD6M2bq/vYM++2YdqR/V++Q1Sl6qn5Nn6ky9Ue/VW3WhzpPXSL1T",
	"Z+pHdZZ8p87UB3WO1BukflKX6oM6UxfmzT9Q8hxtPNpxUPJMXWpS+kMHqfPkefJCXSbP1Ll6q/6H1Ll6",
	"pz4Y0oa8eYTUZfIi+U69TV7YHZbyBiI9VU8Hh5pV7OAj4MLyv7zUXmobwBVBSCKKO3h1qb20agYhsm/0",
	"1yIRbR0tt3zWoybmImZDXnulOV9Y93DHTrPS83EQ8vO0lRhzWDLZWUdlEjio+olOFMNn6Svt9qL3Hn3O",
	"svFox07iEBUitididywDTXRzRlulE3+zZHn8kspJm160sjLJovox1sDBdyfhsXpebCIsDgKi+xZrcZNn",
	"ObhAjwDZaJKkJ3T8mpDb1WsyF+LpwHG0F2UjyWtypOGJ50S+tLyw7UvnEg2OpPM9ylQ0hx/9YfyStdJV",
	"h1/UhzKDmMsLY3zHzl46p7gHjZ6TzWauLRUMj38bbFhCIHME9QQWLN8dmMMQabnEncfVQvl4d7BbttMa",
	"06X7uIywStbKdF8xWA7fG821SYXcSZFm+XrY41N78+pJDPykuHpVANeF3QFr3iiffEzmEmWIOIpkGQwv",
	"nF97yaNMNp8trLRLvYkZ1MyyAet2BYzYoUyy3UByd85gnOPkpB6aD6hv8qqZYCKfCi1UH4iXtt1/+2SN",
	"uH2og7yvzT+Ij1z9HlkPQbSLINTZ0BzY0qwTMKIsVdSVzXa+XNfV8av17e0Sds2x7+AmYUN7dfyi4grc",
	"nEXiNuYznX6MIwj0lMo+6hrnsF1jRHo0JOnEPUtxNlftDpwcuFSdRP1bXap3Bsy/SF6VMH/yEqkP6lL9",
	"V8NzpMG8ep+80vgfJS91S2AQvobyP1W6guR77UXVpFlc2bkmfFS/E3SrEJLpZdIWEP8aLzdZ/43STcQ0",
	"BMVw1W+dUm9gQH7cECr7ZvawrxvXfXOou28j5IfkZfICqUv1H3WhLnULnbweCibd61Zi5I9o304e98tR",
	"1kAjea7eqEu9/ly91/+7UGfqnf6vbpzVhbpIvldvzWNkmusf1GVl43o0FnOwOoZpMkTxSSu9Am8L5OLD",
	"uD6hu+GmeejUfVQop2eVtzyU23fGr8ivIt/S+LUeMVX8tvrFCWUjhC+fYs4VADeBEDNGJwCKtsqYsz/U",
	"L5b96m6Tu5tRYT/3jav8DUgwpks0X9yInwAJJnIQzRF62gcOyC3/8QUViKD0LtLH1P0btFyW9HcCydQs",
	"uW3N7zJAbsSuWsXXil1L959vF3YFEvwi2PUjRaLWkYa9bziz2Epmr0+Xp85Dzdu/1KVuw5KX6meNG69u",
	"09SZ+jAEQ1HyPDu5eZX8ExUI12DNFOXWEaS9Mv7Qjj6nLKD2DxivC0FWL7PfOvRoRuXWqh8derzJ+f1t",
	"DHDreragSnZVoAcgOXW1+9kN+FEWPFVv2WQu8ZEHR+CzyNx8dHDM/fR8t9Nq+fqDPhOyc699r22CKt0v",
	"+5sZeyAxcPLflo/yA4NtSg+28mOA/NFXKcOD3cH/AwAA//926XbJIz0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
