-- +goose Up
CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT,email VARCHAR(255) NOT NULL UNIQUE,name VARCHAR(255) NOT NULL,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE teams (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255) NOT NULL,created_by BIGINT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_teams_created_by FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE team_members (user_id BIGINT NOT NULL,team_id BIGINT NOT NULL,role ENUM('owner','admin','member') NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,team_id),KEY idx_team_members_team_role(team_id,role),CONSTRAINT fk_tm_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_tm_team FOREIGN KEY(team_id) REFERENCES teams(id));
CREATE TABLE tasks (id BIGINT PRIMARY KEY AUTO_INCREMENT,team_id BIGINT NOT NULL,title VARCHAR(255) NOT NULL,description TEXT NOT NULL,status ENUM('todo','in_progress','done') NOT NULL DEFAULT 'todo',assignee_id BIGINT NULL,created_by BIGINT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_tasks_team_status_assignee(team_id,status,assignee_id),KEY idx_tasks_team_updated(team_id,updated_at),KEY idx_tasks_created_month(team_id,created_by,created_at),CONSTRAINT fk_tasks_team FOREIGN KEY(team_id) REFERENCES teams(id),CONSTRAINT fk_tasks_assignee FOREIGN KEY(assignee_id) REFERENCES users(id),CONSTRAINT fk_tasks_created_by FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE task_history (id BIGINT PRIMARY KEY AUTO_INCREMENT,task_id BIGINT NOT NULL,changed_by BIGINT NOT NULL,field VARCHAR(64) NOT NULL,old_value TEXT NOT NULL,new_value TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_history_task_created(task_id,created_at),CONSTRAINT fk_hist_task FOREIGN KEY(task_id) REFERENCES tasks(id),CONSTRAINT fk_hist_user FOREIGN KEY(changed_by) REFERENCES users(id));
CREATE TABLE task_comments (id BIGINT PRIMARY KEY AUTO_INCREMENT,task_id BIGINT NOT NULL,user_id BIGINT NOT NULL,body TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_comments_task_created(task_id,created_at),CONSTRAINT fk_comments_task FOREIGN KEY(task_id) REFERENCES tasks(id),CONSTRAINT fk_comments_user FOREIGN KEY(user_id) REFERENCES users(id));
-- +goose Down
DROP TABLE task_comments; DROP TABLE task_history; DROP TABLE tasks; DROP TABLE team_members; DROP TABLE teams; DROP TABLE users;
